import type {
  Car,
  CarDocument,
  FleetAccess,
  Maintenance,
  NotificationItem,
  Profile,
  Rental,
} from '@/types/models'

const now = new Date()
const nowIso = now.toISOString()

function dateOffset(days: number) {
  const date = new Date()
  date.setHours(12, 0, 0, 0)
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

export const demoProfile: Profile = {
  id: 'demo-user',
  fullName: 'Popescu Ion',
  email: 'demo@mycars.ro',
  createdAt: nowIso,
}

export const demoCars: Car[] = [
  {
    id: 'car-1',
    ownerId: 'demo-user',
    licensePlate: 'B-123-MYC',
    brand: 'Skoda',
    model: 'Octavia',
    year: 2021,
    color: 'Gri',
    engineHp: 150,
    engineKw: 112,
    engineDisplacement: 1968,
    transmission: 'automatic',
    chassisNumber: 'TMBBL7NE2M1234567',
    category: 'rent',
    status: 'available',
    purchasePrice: 18200,
    purchaseCurrency: 'EUR',
    notes: 'Masina ideala pentru inchiriere pe termen mediu.',
    serviceReturnDate: undefined,
    currentKm: 84750,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'car-2',
    ownerId: 'demo-user',
    licensePlate: 'B-456-BLT',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2020,
    color: 'Alb',
    engineHp: 122,
    engineKw: 91,
    engineDisplacement: 1798,
    transmission: 'automatic',
    chassisNumber: 'NMTBZ3BE70R654321',
    category: 'bolt',
    status: 'rented',
    purchasePrice: 16900,
    purchaseCurrency: 'EUR',
    notes: 'Masina activa pe platforma, cu client recurent.',
    serviceReturnDate: undefined,
    currentKm: 124320,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'car-3',
    ownerId: 'demo-user',
    licensePlate: 'B-789-SRV',
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2019,
    color: 'Negru',
    engineHp: 190,
    engineKw: 142,
    engineDisplacement: 1984,
    transmission: 'manual',
    chassisNumber: 'WVWZZZ3CZKE999111',
    category: 'service_replacement',
    status: 'maintenance',
    purchasePrice: 15400,
    purchaseCurrency: 'EUR',
    notes: 'Programata pentru revizie completa si schimb consumabile.',
    serviceReturnDate: dateOffset(1),
    currentKm: 167000,
    createdAt: nowIso,
    updatedAt: nowIso,
  },
]

export const demoDocuments: CarDocument[] = [
  {
    id: 'doc-1',
    carId: 'car-1',
    type: 'RCA',
    customName: 'RCA anual',
    issueDate: dateOffset(-320),
    expiryDate: dateOffset(18),
    isMandatory: true,
    createdAt: nowIso,
  },
  {
    id: 'doc-4',
    carId: 'car-1',
    type: 'ITP',
    customName: 'Inspectie tehnica periodica',
    issueDate: dateOffset(-250),
    expiryDate: dateOffset(82),
    isMandatory: true,
    createdAt: nowIso,
  },
  {
    id: 'doc-2',
    carId: 'car-2',
    type: 'ITP',
    customName: 'Inspectie tehnica',
    issueDate: dateOffset(-330),
    expiryDate: dateOffset(6),
    isMandatory: true,
    createdAt: nowIso,
  },
  {
    id: 'doc-5',
    carId: 'car-2',
    type: 'RCA',
    customName: 'RCA anual',
    issueDate: dateOffset(-290),
    expiryDate: dateOffset(39),
    isMandatory: true,
    createdAt: nowIso,
  },
  {
    id: 'doc-3',
    carId: 'car-3',
    type: 'ROVINIETA',
    customName: 'Rovinieta',
    issueDate: dateOffset(-365),
    expiryDate: dateOffset(-5),
    isMandatory: false,
    createdAt: nowIso,
  },
  {
    id: 'doc-6',
    carId: 'car-3',
    type: 'ITP',
    customName: 'Inspectie tehnica periodica',
    issueDate: dateOffset(-310),
    expiryDate: dateOffset(31),
    isMandatory: true,
    createdAt: nowIso,
  },
  {
    id: 'doc-7',
    carId: 'car-3',
    type: 'RCA',
    customName: 'RCA anual',
    issueDate: dateOffset(-280),
    expiryDate: dateOffset(14),
    isMandatory: true,
    createdAt: nowIso,
  },
]

export const demoRentals: Rental[] = [
  {
    id: 'rental-1',
    carId: 'car-2',
    renterName: 'Mihai',
    renterSurname: 'Ionescu',
    renterCnp: '1960212123456',
    startDate: dateOffset(-10),
    endDate: dateOffset(12),
    advancePayment: 1000,
    status: 'active',
    notes: 'Client recurent, contract fara incidente.',
    kmStart: 121000,
    kmEnd: 0,
    createdAt: nowIso,
    updatedAt: nowIso,
    segments: [
      {
        id: 'seg-1',
        rentalId: 'rental-1',
        pricePerUnit: 500,
        priceUnit: 'week',
        startDate: dateOffset(-10),
        endDate: dateOffset(-1),
        createdAt: nowIso,
      },
      {
        id: 'seg-2',
        rentalId: 'rental-1',
        pricePerUnit: 600,
        priceUnit: 'week',
        startDate: dateOffset(0),
        endDate: dateOffset(12),
        createdAt: nowIso,
      },
    ],
    photos: [],
  },
]

export const demoMaintenance: Maintenance[] = [
  {
    id: 'mnt-1',
    carId: 'car-3',
    type: 'repair',
    description: 'Revizie completa + schimb ulei',
    cost: 1450,
    datePerformed: dateOffset(-1),
    expectedCompletionDate: dateOffset(1),
    kmAtService: 166500,
    notes: 'Include filtre, diagnoza si verificare frane.',
    createdAt: nowIso,
    documents: [],
  },
]

export const demoInvites: FleetAccess[] = [
  {
    id: 'acc-1',
    ownerId: 'demo-user',
    invitedEmail: 'coleg@mycars.ro',
    role: 'editor',
    createdAt: nowIso,
  },
]

export const demoNotifications: NotificationItem[] = [
  {
    id: 'not-1',
    userId: 'demo-user',
    carId: 'car-2',
    documentId: 'doc-2',
    title: 'ITP expira curand',
    message: 'ITP pentru B-456-BLT expira in urmatoarele 7 zile.',
    type: 'expiry_7',
    isRead: false,
    createdAt: nowIso,
  },
  {
    id: 'not-2',
    userId: 'demo-user',
    carId: 'car-3',
    documentId: 'doc-3',
    title: 'Rovinieta expirata',
    message: 'Rovinieta pentru B-789-SRV este expirata.',
    type: 'expired',
    isRead: false,
    createdAt: nowIso,
  },
]
