import type {
  Car,
  CarDocument,
  FleetAccess,
  Maintenance,
  NotificationItem,
  Profile,
  Rental,
} from '@/types/models'

const now = new Date().toISOString()

export const demoProfile: Profile = {
  id: 'demo-user',
  fullName: 'Popescu Ion',
  email: 'demo@mycars.ro',
  createdAt: now,
}

export const demoCars: Car[] = [
  {
    id: 'car-1',
    ownerId: 'demo-user',
    licensePlate: 'B-123-MYC',
    brand: 'Skoda',
    model: 'Octavia',
    year: 2021,
    color: 'Gri',
    engineHp: 150,
    engineKw: 112,
    engineDisplacement: 1968,
    transmission: 'automatic',
    chassisNumber: 'TMBBL7NE2M1234567',
    category: 'rent',
    status: 'available',
    purchasePrice: 18200,
    purchaseCurrency: 'EUR',
    notes: 'Mașină ideală pentru închiriere pe termen mediu.',
    currentKm: 84750,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'car-2',
    ownerId: 'demo-user',
    licensePlate: 'B-456-BLT',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2020,
    color: 'Alb',
    engineHp: 122,
    engineKw: 91,
    engineDisplacement: 1798,
    transmission: 'automatic',
    chassisNumber: 'NMTBZ3BE70R654321',
    category: 'bolt',
    status: 'rented',
    purchasePrice: 16900,
    purchaseCurrency: 'EUR',
    notes: 'Activă pe Bolt cu client recurent.',
    currentKm: 124320,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'car-3',
    ownerId: 'demo-user',
    licensePlate: 'B-789-SRV',
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2019,
    color: 'Negru',
    engineHp: 190,
    engineKw: 142,
    engineDisplacement: 1984,
    transmission: 'manual',
    chassisNumber: 'WVWZZZ3CZKE999111',
    category: 'service_replacement',
    status: 'maintenance',
    purchasePrice: 15400,
    purchaseCurrency: 'EUR',
    notes: 'Programată pentru revizie completă.',
    currentKm: 167000,
    createdAt: now,
    updatedAt: now,
  },
]

export const demoDocuments: CarDocument[] = [
  {
    id: 'doc-1',
    carId: 'car-1',
    type: 'RCA',
    customName: 'RCA anual',
    issueDate: '2026-01-10',
    expiryDate: '2026-04-05',
    isMandatory: true,
    createdAt: now,
  },
  {
    id: 'doc-2',
    carId: 'car-2',
    type: 'ITP',
    customName: 'Inspecție tehnică',
    issueDate: '2025-10-10',
    expiryDate: '2026-03-21',
    isMandatory: true,
    createdAt: now,
  },
  {
    id: 'doc-3',
    carId: 'car-3',
    type: 'ROVINIETA',
    customName: 'Rovinietă',
    issueDate: '2025-03-01',
    expiryDate: '2026-03-15',
    isMandatory: true,
    createdAt: now,
  },
]

export const demoRentals: Rental[] = [
  {
    id: 'rental-1',
    carId: 'car-2',
    renterName: 'Mihai',
    renterSurname: 'Ionescu',
    renterCnp: '1960212123456',
    startDate: '2026-02-01',
    endDate: '2026-04-30',
    advancePayment: 1000,
    status: 'active',
    notes: 'Client recurent.',
    kmStart: 121000,
    kmEnd: 0,
    createdAt: now,
    updatedAt: now,
    segments: [
      {
        id: 'seg-1',
        rentalId: 'rental-1',
        pricePerUnit: 500,
        priceUnit: 'week',
        startDate: '2026-02-01',
        endDate: '2026-03-20',
        createdAt: now,
      },
      {
        id: 'seg-2',
        rentalId: 'rental-1',
        pricePerUnit: 600,
        priceUnit: 'week',
        startDate: '2026-03-21',
        endDate: '2026-04-30',
        createdAt: now,
      },
    ],
    photos: [],
  },
]

export const demoMaintenance: Maintenance[] = [
  {
    id: 'mnt-1',
    carId: 'car-3',
    type: 'service',
    description: 'Revizie completă + schimb ulei',
    cost: 1450,
    datePerformed: '2026-03-10',
    kmAtService: 166500,
    notes: 'Include filtre și diagnoză.',
    createdAt: now,
    documents: [],
  },
]

export const demoInvites: FleetAccess[] = [
  {
    id: 'acc-1',
    ownerId: 'demo-user',
    invitedEmail: 'coleg@mycars.ro',
    role: 'editor',
    createdAt: now,
  },
]

export const demoNotifications: NotificationItem[] = [
  {
    id: 'not-1',
    userId: 'demo-user',
    carId: 'car-2',
    documentId: 'doc-2',
    title: 'ITP expiră curând',
    message: 'ITP pentru B-456-BLT expiră în următoarele 7 zile.',
    type: 'expiry_7',
    isRead: false,
    createdAt: now,
  },
  {
    id: 'not-2',
    userId: 'demo-user',
    carId: 'car-3',
    documentId: 'doc-3',
    title: 'Rovinietă expirată',
    message: 'Rovinietă pentru B-789-SRV este expirată.',
    type: 'expired',
    isRead: false,
    createdAt: now,
  },
]
