import type {
  Car,
  CarDocument,
  FleetAccess,
  FleetReportRecord,
  Maintenance,
  NotificationItem,
  Profile,
  Rental,
} from '@/types/models'

const now = new Date()
const nowIso = now.toISOString()

function dateOffset(days: number) {
  const date = new Date()
  date.setHours(12, 0, 0, 0)
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

function isoOffset(days: number) {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

export const demoProfile: Profile = {
  id: 'demo-user',
  fullName: 'Popescu Ion',
  email: 'demo@mycars.ro',
  createdAt: nowIso,
}

export const demoCars: Car[] = [
  {
    id: 'car-1',
    ownerId: 'demo-user',
    licensePlate: 'B-104-LGN',
    brand: 'Dacia',
    model: 'Logan',
    year: 2019,
    color: 'Alb',
    engineHp: 90,
    engineKw: 67,
    engineDisplacement: 999,
    transmission: 'manual',
    chassisNumber: 'UU1LSDCLXML234567',
    category: 'rent',
    status: 'available',
    purchasePrice: 7200,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1300,
    notes: 'Bara fata atinsa, volan uzat.',
    currentKm: 132000,
    createdAt: isoOffset(-520),
    updatedAt: nowIso,
  },
  {
    id: 'car-2',
    ownerId: 'demo-user',
    licensePlate: 'B-217-SKD',
    brand: 'Skoda',
    model: 'Octavia',
    year: 2021,
    color: 'Gri',
    engineHp: 150,
    engineKw: 112,
    engineDisplacement: 1968,
    transmission: 'automatic',
    chassisNumber: 'TMBJJ7NE9MZ112233',
    category: 'rent',
    status: 'available',
    purchasePrice: 18200,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1850,
    notes: 'Parbriz ciobit dreapta, usa spate zgariata.',
    currentKm: 84750,
    createdAt: isoOffset(-430),
    updatedAt: nowIso,
  },
  {
    id: 'car-3',
    ownerId: 'demo-user',
    licensePlate: 'PH-33-VWP',
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2019,
    color: 'Negru',
    engineHp: 190,
    engineKw: 142,
    engineDisplacement: 1984,
    transmission: 'manual',
    chassisNumber: 'WVWZZZ3CZLE445566',
    category: 'service_replacement',
    status: 'available',
    purchasePrice: 15400,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1950,
    notes: 'Aripa stanga zgariata, capota matuita.',
    currentKm: 167000,
    createdAt: isoOffset(-480),
    updatedAt: nowIso,
  },
  {
    id: 'car-4',
    ownerId: 'demo-user',
    licensePlate: 'B-350-BLT',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2020,
    color: 'Alb perlat',
    engineHp: 122,
    engineKw: 91,
    engineDisplacement: 1798,
    transmission: 'automatic',
    chassisNumber: 'NMTBZ3BE80R778899',
    category: 'bolt',
    status: 'available',
    purchasePrice: 16900,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 2100,
    notes: 'Jante dreapta zgariate, bara spate atinsa.',
    currentKm: 124320,
    createdAt: isoOffset(-170),
    updatedAt: nowIso,
  },
  {
    id: 'car-5',
    ownerId: 'demo-user',
    licensePlate: 'CJ-28-UBR',
    brand: 'Hyundai',
    model: 'i30',
    year: 2020,
    color: 'Argintiu',
    engineHp: 120,
    engineKw: 89,
    engineDisplacement: 1368,
    transmission: 'manual',
    chassisNumber: 'TMAD381AAMZ990011',
    category: 'uber',
    status: 'available',
    purchasePrice: 11200,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1650,
    notes: 'Stergatoare slabe, bancheta patata.',
    currentKm: 98000,
    createdAt: isoOffset(-150),
    updatedAt: nowIso,
  },
  {
    id: 'car-6',
    ownerId: 'demo-user',
    licensePlate: 'SB-19-MGN',
    brand: 'Renault',
    model: 'Megane',
    year: 2021,
    color: 'Albastru',
    engineHp: 115,
    engineKw: 86,
    engineDisplacement: 1461,
    transmission: 'manual',
    chassisNumber: 'VF1RFA0BXFN223344',
    category: 'rent',
    status: 'available',
    purchasePrice: 11900,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1750,
    notes: 'Usa stanga zgariata, cheder dreapta desprins.',
    currentKm: 87000,
    createdAt: isoOffset(-320),
    updatedAt: nowIso,
  },
  {
    id: 'car-7',
    ownerId: 'demo-user',
    licensePlate: 'AG-77-DST',
    brand: 'Dacia',
    model: 'Duster',
    year: 2020,
    color: 'Portocaliu',
    engineHp: 115,
    engineKw: 86,
    engineDisplacement: 1461,
    transmission: 'manual',
    chassisNumber: 'UU1HSDCV5ML556677',
    category: 'personal',
    status: 'available',
    purchasePrice: 12600,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1350,
    notes: 'Bara fata atinsa, geam spate stanga blocat.',
    currentKm: 61000,
    createdAt: isoOffset(-120),
    updatedAt: nowIso,
  },
  {
    id: 'car-8',
    ownerId: 'demo-user',
    licensePlate: 'TM-46-FCS',
    brand: 'Ford',
    model: 'Focus',
    year: 2019,
    color: 'Alb',
    engineHp: 125,
    engineKw: 93,
    engineDisplacement: 998,
    transmission: 'manual',
    chassisNumber: 'WF0AXXWPMAF889900',
    category: 'rent',
    status: 'available',
    purchasePrice: 9800,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1580,
    notes: 'Ambreiaj tine sus, bate pe fata.',
    currentKm: 132000,
    createdAt: isoOffset(-650),
    updatedAt: nowIso,
  },
  {
    id: 'car-9',
    ownerId: 'demo-user',
    licensePlate: 'BV-58-CDD',
    brand: 'Kia',
    model: 'Ceed',
    year: 2022,
    color: 'Rosu',
    engineHp: 140,
    engineKw: 104,
    engineDisplacement: 1353,
    transmission: 'automatic',
    chassisNumber: 'U5YFF24128L334455',
    category: 'bolt',
    status: 'available',
    purchasePrice: 17400,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 2250,
    notes: 'Anvelope Michelin DOT 2025, jante zgariate.',
    currentKm: 69000,
    createdAt: isoOffset(-110),
    updatedAt: nowIso,
  },
  {
    id: 'car-10',
    ownerId: 'demo-user',
    licensePlate: 'SV-12-ATR',
    brand: 'Opel',
    model: 'Astra',
    year: 2020,
    color: 'Alb',
    engineHp: 110,
    engineKw: 82,
    engineDisplacement: 1496,
    transmission: 'manual',
    chassisNumber: 'W0LPF6EDXAG667788',
    category: 'rent',
    status: 'available',
    purchasePrice: 10500,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1600,
    notes: 'Baterie slaba, probleme electrice.',
    currentKm: 116000,
    createdAt: isoOffset(-400),
    updatedAt: nowIso,
  },
  {
    id: 'car-11',
    ownerId: 'demo-user',
    licensePlate: 'B-501-BMW',
    brand: 'BMW',
    model: 'Seria 3',
    year: 2019,
    color: 'Albastru inchis',
    engineHp: 190,
    engineKw: 142,
    engineDisplacement: 1995,
    transmission: 'automatic',
    chassisNumber: 'WBA8E9C50HK112244',
    category: 'general',
    status: 'available',
    purchasePrice: 24600,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 4100,
    notes: 'Capota lac sarit, prag dreapta zgariat.',
    currentKm: 142000,
    createdAt: isoOffset(-870),
    updatedAt: nowIso,
  },
  {
    id: 'car-12',
    ownerId: 'demo-user',
    licensePlate: 'IS-64-SPB',
    brand: 'Skoda',
    model: 'Superb',
    year: 2019,
    color: 'Gri',
    engineHp: 190,
    engineKw: 142,
    engineDisplacement: 1968,
    transmission: 'automatic',
    chassisNumber: 'TMBAJ7NP5JZ556688',
    category: 'service_replacement',
    status: 'available',
    purchasePrice: 19600,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 3150,
    notes: 'Bara spate atinsa, senzor parcare spate intermitent.',
    currentKm: 160000,
    createdAt: isoOffset(-360),
    updatedAt: nowIso,
  },
  {
    id: 'car-13',
    ownerId: 'demo-user',
    licensePlate: 'CT-25-CVC',
    brand: 'Honda',
    model: 'Civic',
    year: 2020,
    color: 'Alb',
    engineHp: 182,
    engineKw: 136,
    engineDisplacement: 1498,
    transmission: 'manual',
    chassisNumber: 'SHHFK2750HU778811',
    category: 'uber',
    status: 'available',
    purchasePrice: 18100,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 2350,
    notes: 'Bate pe fata la denivelari, volan uzat.',
    currentKm: 95000,
    createdAt: isoOffset(-135),
    updatedAt: nowIso,
  },
  {
    id: 'car-14',
    ownerId: 'demo-user',
    licensePlate: 'MS-83-LEN',
    brand: 'Seat',
    model: 'Leon',
    year: 2018,
    color: 'Alb',
    engineHp: 150,
    engineKw: 112,
    engineDisplacement: 1498,
    transmission: 'manual',
    chassisNumber: 'VSSZZZ5FZFR990022',
    category: 'general',
    status: 'archived',
    purchasePrice: 13800,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1850,
    notes: 'Vanduta, reparatii prea dese.',
    currentKm: 178000,
    archivedAt: isoOffset(-40),
    createdAt: isoOffset(-460),
    updatedAt: isoOffset(-40),
  },
  {
    id: 'car-15',
    ownerId: 'demo-user',
    licensePlate: 'DB-14-PJT',
    brand: 'Peugeot',
    model: '308',
    year: 2017,
    color: 'Gri inchis',
    engineHp: 130,
    engineKw: 97,
    engineDisplacement: 1499,
    transmission: 'automatic',
    chassisNumber: 'VF3LBHZAP1Z334477',
    category: 'personal',
    status: 'archived',
    purchasePrice: 13700,
    purchaseCurrency: 'EUR',
    annualInsuranceCost: 1950,
    notes: 'Km mare, reparatii prea dese.',
    currentKm: 145000,
    archivedAt: isoOffset(-200),
    createdAt: isoOffset(-600),
    updatedAt: isoOffset(-200),
  },
]

export const demoDocuments: CarDocument[] = [
  // car-1 - Dacia Logan
  { id: 'doc-1', carId: 'car-1', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(150), isMandatory: true, createdAt: nowIso },
  { id: 'doc-2', carId: 'car-1', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(5), isMandatory: true, createdAt: nowIso },
  { id: 'doc-3', carId: 'car-1', type: 'ROVINIETA', customName: 'Rovinieta', issueDate: dateOffset(-40), expiryDate: dateOffset(-5), isMandatory: false, createdAt: nowIso },

  // car-2 - Skoda Octavia
  { id: 'doc-4', carId: 'car-2', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(-10), isMandatory: true, createdAt: nowIso },
  { id: 'doc-5', carId: 'car-2', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(20), isMandatory: true, createdAt: nowIso },
  { id: 'doc-6', carId: 'car-2', type: 'CI_VEHICUL', customName: 'Carte identitate vehicul', isMandatory: false, createdAt: nowIso },

  // car-3 - VW Passat
  { id: 'doc-7', carId: 'car-3', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(45), isMandatory: true, createdAt: nowIso },
  { id: 'doc-8', carId: 'car-3', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(-3), isMandatory: true, createdAt: nowIso },
  { id: 'doc-9', carId: 'car-3', type: 'CASCO', customName: 'CASCO Full', issueDate: dateOffset(-165), expiryDate: dateOffset(200), isMandatory: false, createdAt: nowIso },

  // car-4 - Toyota Corolla
  { id: 'doc-10', carId: 'car-4', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(9), isMandatory: true, createdAt: nowIso },
  { id: 'doc-11', carId: 'car-4', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(90), isMandatory: true, createdAt: nowIso },
  { id: 'doc-12', carId: 'car-4', type: 'ROVINIETA', customName: 'Rovinieta', issueDate: dateOffset(-350), expiryDate: dateOffset(-20), isMandatory: false, createdAt: nowIso },

  // car-5 - Hyundai i30
  { id: 'doc-13', carId: 'car-5', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(200), isMandatory: true, createdAt: nowIso },
  { id: 'doc-14', carId: 'car-5', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(12), isMandatory: true, createdAt: nowIso },
  { id: 'doc-15', carId: 'car-5', type: 'ROVINIETA', customName: 'Rovinieta', issueDate: dateOffset(-15), expiryDate: dateOffset(15), isMandatory: false, createdAt: nowIso },

  // car-6 - Renault Megane
  { id: 'doc-16', carId: 'car-6', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(3), isMandatory: true, createdAt: nowIso },
  { id: 'doc-17', carId: 'car-6', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(60), isMandatory: true, createdAt: nowIso },
  { id: 'doc-18', carId: 'car-6', type: 'TALON', customName: 'Talon inmatriculare', isMandatory: false, createdAt: nowIso },

  // car-7 - Dacia Duster
  { id: 'doc-19', carId: 'car-7', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(100), isMandatory: true, createdAt: nowIso },
  { id: 'doc-20', carId: 'car-7', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(25), isMandatory: true, createdAt: nowIso },
  { id: 'doc-21', carId: 'car-7', type: 'OTHER', customName: 'Procura auto', issueDate: dateOffset(-2), expiryDate: dateOffset(365), isMandatory: false, createdAt: nowIso },

  // car-8 - Ford Focus
  { id: 'doc-22', carId: 'car-8', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(-1), isMandatory: true, createdAt: nowIso },
  { id: 'doc-23', carId: 'car-8', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(40), isMandatory: true, createdAt: nowIso },

  // car-9 - Kia Ceed
  { id: 'doc-24', carId: 'car-9', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(18), isMandatory: true, createdAt: nowIso },
  { id: 'doc-25', carId: 'car-9', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(7), isMandatory: true, createdAt: nowIso },
  { id: 'doc-26', carId: 'car-9', type: 'ROVINIETA', customName: 'Rovinieta', issueDate: dateOffset(-28), expiryDate: dateOffset(2), isMandatory: false, createdAt: nowIso },

  // car-10 - Opel Astra
  { id: 'doc-27', carId: 'car-10', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(120), isMandatory: true, createdAt: nowIso },
  { id: 'doc-28', carId: 'car-10', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(-15), isMandatory: true, createdAt: nowIso },
  { id: 'doc-29', carId: 'car-10', type: 'CI_VEHICUL', customName: 'Carte identitate vehicul', isMandatory: false, createdAt: nowIso },

  // car-11 - BMW Seria 3
  { id: 'doc-30', carId: 'car-11', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(6), isMandatory: true, createdAt: nowIso },
  { id: 'doc-31', carId: 'car-11', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(180), isMandatory: true, createdAt: nowIso },
  { id: 'doc-32', carId: 'car-11', type: 'CASCO', customName: 'CASCO Full', issueDate: dateOffset(-275), expiryDate: dateOffset(90), isMandatory: false, createdAt: nowIso },
  { id: 'doc-33', carId: 'car-11', type: 'OTHER', customName: 'Contract de leasing', isMandatory: false, createdAt: nowIso },

  // car-12 - Skoda Superb
  { id: 'doc-34', carId: 'car-12', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(29), isMandatory: true, createdAt: nowIso },
  { id: 'doc-35', carId: 'car-12', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(80), isMandatory: true, createdAt: nowIso },
  { id: 'doc-36', carId: 'car-12', type: 'CASCO', customName: 'CASCO Full', issueDate: dateOffset(-360), expiryDate: dateOffset(5), isMandatory: false, createdAt: nowIso },

  // car-13 - Honda Civic
  { id: 'doc-37', carId: 'car-13', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-330), expiryDate: dateOffset(250), isMandatory: true, createdAt: nowIso },
  { id: 'doc-38', carId: 'car-13', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-300), expiryDate: dateOffset(13), isMandatory: true, createdAt: nowIso },
  { id: 'doc-39', carId: 'car-13', type: 'TALON', customName: 'Talon inmatriculare', isMandatory: false, createdAt: nowIso },

  // car-14 - Seat Leon (arhivata)
  { id: 'doc-40', carId: 'car-14', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-425), expiryDate: dateOffset(-60), isMandatory: true, createdAt: nowIso },
  { id: 'doc-41', carId: 'car-14', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-415), expiryDate: dateOffset(-50), isMandatory: true, createdAt: nowIso },

  // car-15 - Peugeot 308 (arhivata)
  { id: 'doc-42', carId: 'car-15', type: 'RCA', customName: 'RCA anual', issueDate: dateOffset(-585), expiryDate: dateOffset(-220), isMandatory: true, createdAt: nowIso },
  { id: 'doc-43', carId: 'car-15', type: 'ITP', customName: 'Inspectie tehnica periodica', issueDate: dateOffset(-575), expiryDate: dateOffset(-210), isMandatory: true, createdAt: nowIso },
  { id: 'doc-44', carId: 'car-15', type: 'OTHER', customName: 'Adeverinta radiere provizorie', issueDate: dateOffset(-105), expiryDate: dateOffset(-100), isMandatory: false, createdAt: nowIso },
]

export const demoRentals: Rental[] = [
  {
    id: 'rental-1',
    carId: 'car-2',
    renterName: 'Mihai',
    renterSurname: 'Ionescu',
    renterCnp: '1900101010001',
    startDate: dateOffset(-10),
    endDate: dateOffset(12),
    advancePayment: 1400,
    status: 'active',
    notes: 'Zgarietura bara spate.',
    kmStart: 82600,
    createdAt: isoOffset(-10),
    updatedAt: isoOffset(-10),
    segments: [
      { id: 'seg-1', rentalId: 'rental-1', pricePerUnit: 750, priceUnit: 'week', startDate: dateOffset(-10), endDate: dateOffset(-1), createdAt: isoOffset(-10) },
      { id: 'seg-2', rentalId: 'rental-1', pricePerUnit: 850, priceUnit: 'week', startDate: dateOffset(0), endDate: dateOffset(12), createdAt: isoOffset(-10) },
    ],
    photos: [],
  },
  {
    id: 'rental-2',
    carId: 'car-4',
    renterName: 'Ana',
    renterSurname: 'Petrescu',
    renterCnp: '2900101020002',
    startDate: dateOffset(-3),
    endDate: dateOffset(4),
    advancePayment: 350,
    status: 'active',
    notes: 'Jante fata zgariate.',
    kmStart: 124320,
    createdAt: isoOffset(-3),
    updatedAt: isoOffset(-3),
    segments: [
      { id: 'seg-3', rentalId: 'rental-2', pricePerUnit: 260, priceUnit: 'day', startDate: dateOffset(-3), endDate: dateOffset(4), createdAt: isoOffset(-3) },
    ],
    photos: [],
  },
  {
    id: 'rental-3',
    carId: 'car-5',
    renterName: 'Vlad',
    renterSurname: 'Stan',
    renterCnp: '1900101030003',
    startDate: dateOffset(-5),
    endDate: dateOffset(9),
    advancePayment: 500,
    status: 'active',
    notes: 'Anvelope Goodyear DOT 2025.',
    kmStart: 98000,
    createdAt: isoOffset(-5),
    updatedAt: isoOffset(-5),
    segments: [
      { id: 'seg-4', rentalId: 'rental-3', pricePerUnit: 215, priceUnit: 'day', startDate: dateOffset(-5), endDate: dateOffset(-1), createdAt: isoOffset(-5) },
      { id: 'seg-5', rentalId: 'rental-3', pricePerUnit: 235, priceUnit: 'day', startDate: dateOffset(0), endDate: dateOffset(9), createdAt: isoOffset(-5) },
    ],
    photos: [],
  },
  {
    id: 'rental-4',
    carId: 'car-1',
    renterName: 'Cristian',
    renterSurname: 'Radu',
    renterCnp: '2900101040004',
    startDate: dateOffset(-350),
    endDate: dateOffset(-320),
    advancePayment: 600,
    status: 'completed',
    notes: 'Bara fata atinsa.',
    kmStart: 122000,
    kmEnd: 125200,
    createdAt: isoOffset(-350),
    updatedAt: isoOffset(-320),
    segments: [
      { id: 'seg-6', rentalId: 'rental-4', pricePerUnit: 1900, priceUnit: 'month', startDate: dateOffset(-350), endDate: dateOffset(-320), createdAt: isoOffset(-350) },
    ],
    photos: [],
  },
  {
    id: 'rental-5',
    carId: 'car-3',
    renterName: 'Diana',
    renterSurname: 'Tudor',
    renterCnp: '1900101050005',
    startDate: dateOffset(-300),
    endDate: dateOffset(-280),
    advancePayment: 700,
    status: 'completed',
    notes: 'Parbriz ciobit dreapta.',
    kmStart: 158000,
    kmEnd: 160200,
    createdAt: isoOffset(-300),
    updatedAt: isoOffset(-280),
    segments: [
      { id: 'seg-7', rentalId: 'rental-5', pricePerUnit: 1000, priceUnit: 'week', startDate: dateOffset(-300), endDate: dateOffset(-280), createdAt: isoOffset(-300) },
    ],
    photos: [],
  },
  {
    id: 'rental-6',
    carId: 'car-6',
    renterName: 'George',
    renterSurname: 'Marin',
    renterCnp: '2900101060006',
    startDate: dateOffset(-230),
    endDate: dateOffset(-200),
    advancePayment: 1050,
    status: 'completed',
    notes: 'Usa spate stanga zgariata.',
    kmStart: 80500,
    kmEnd: 84200,
    createdAt: isoOffset(-230),
    updatedAt: isoOffset(-200),
    segments: [
      { id: 'seg-8', rentalId: 'rental-6', pricePerUnit: 2100, priceUnit: 'month', startDate: dateOffset(-230), endDate: dateOffset(-200), createdAt: isoOffset(-230) },
    ],
    photos: [],
  },
  {
    id: 'rental-7',
    carId: 'car-8',
    renterName: 'Elena',
    renterSurname: 'Georgescu',
    renterCnp: '1900101070007',
    startDate: dateOffset(-600),
    endDate: dateOffset(-580),
    advancePayment: 650,
    status: 'completed',
    notes: 'Oglinda stanga zgariata.',
    kmStart: 118000,
    kmEnd: 120300,
    createdAt: isoOffset(-600),
    updatedAt: isoOffset(-580),
    segments: [
      { id: 'seg-9', rentalId: 'rental-7', pricePerUnit: 950, priceUnit: 'week', startDate: dateOffset(-600), endDate: dateOffset(-580), createdAt: isoOffset(-600) },
    ],
    photos: [],
  },
  {
    id: 'rental-8',
    carId: 'car-9',
    renterName: 'Sorin',
    renterSurname: 'Ilie',
    renterCnp: '2900101080008',
    startDate: dateOffset(-60),
    endDate: dateOffset(-55),
    advancePayment: 250,
    status: 'completed',
    notes: 'Prag stanga zgariat.',
    kmStart: 66000,
    kmEnd: 66450,
    createdAt: isoOffset(-60),
    updatedAt: isoOffset(-55),
    segments: [
      { id: 'seg-10', rentalId: 'rental-8', pricePerUnit: 140, priceUnit: 'day', startDate: dateOffset(-60), endDate: dateOffset(-55), createdAt: isoOffset(-60) },
    ],
    photos: [],
  },
  {
    id: 'rental-9',
    carId: 'car-9',
    renterName: 'Alexandru',
    renterSurname: 'Nistor',
    renterCnp: '1900101090009',
    startDate: dateOffset(-30),
    endDate: dateOffset(-27),
    advancePayment: 180,
    status: 'completed',
    notes: 'Geam spate stanga merge greu.',
    kmStart: 67200,
    kmEnd: 67550,
    createdAt: isoOffset(-30),
    updatedAt: isoOffset(-27),
    segments: [
      { id: 'seg-11', rentalId: 'rental-9', pricePerUnit: 150, priceUnit: 'day', startDate: dateOffset(-30), endDate: dateOffset(-27), createdAt: isoOffset(-30) },
    ],
    photos: [],
  },
  {
    id: 'rental-10',
    carId: 'car-9',
    renterName: 'Larisa',
    renterSurname: 'Dumitrescu',
    renterCnp: '2900101100010',
    startDate: dateOffset(-20),
    endDate: dateOffset(-15),
    advancePayment: 0,
    status: 'cancelled',
    notes: 'Rezervare anulata.',
    createdAt: isoOffset(-22),
    updatedAt: isoOffset(-21),
    segments: [
      { id: 'seg-12', rentalId: 'rental-10', pricePerUnit: 145, priceUnit: 'day', startDate: dateOffset(-20), endDate: dateOffset(-15), createdAt: isoOffset(-22) },
    ],
    photos: [],
  },
  {
    id: 'rental-11',
    carId: 'car-10',
    renterName: 'Paul',
    renterSurname: 'Neagu',
    renterCnp: '1900101110011',
    startDate: dateOffset(-280),
    endDate: dateOffset(-260),
    advancePayment: 720,
    status: 'completed',
    notes: 'Oglinda dreapta zgariata.',
    kmStart: 110000,
    kmEnd: 112800,
    createdAt: isoOffset(-280),
    updatedAt: isoOffset(-260),
    segments: [
      { id: 'seg-13', rentalId: 'rental-11', pricePerUnit: 900, priceUnit: 'week', startDate: dateOffset(-280), endDate: dateOffset(-260), createdAt: isoOffset(-280) },
    ],
    photos: [],
  },
  {
    id: 'rental-12',
    carId: 'car-11',
    renterName: 'Andrei',
    renterSurname: 'Vasilescu',
    renterCnp: '2900101120012',
    startDate: dateOffset(-700),
    endDate: dateOffset(-670),
    advancePayment: 1900,
    status: 'completed',
    notes: 'Anvelope Michelin DOT 2025.',
    kmStart: 128000,
    kmEnd: 131000,
    createdAt: isoOffset(-700),
    updatedAt: isoOffset(-670),
    segments: [
      { id: 'seg-14', rentalId: 'rental-12', pricePerUnit: 3200, priceUnit: 'month', startDate: dateOffset(-700), endDate: dateOffset(-670), createdAt: isoOffset(-700) },
    ],
    photos: [],
  },
  {
    id: 'rental-13',
    carId: 'car-12',
    renterName: 'Ramona',
    renterSurname: 'Dragomir',
    renterCnp: '1900101130013',
    startDate: dateOffset(-300),
    endDate: dateOffset(-295),
    advancePayment: 300,
    status: 'completed',
    notes: 'Prag dreapta zgariat.',
    kmStart: 156000,
    kmEnd: 156650,
    createdAt: isoOffset(-300),
    updatedAt: isoOffset(-295),
    segments: [
      { id: 'seg-15', rentalId: 'rental-13', pricePerUnit: 260, priceUnit: 'day', startDate: dateOffset(-300), endDate: dateOffset(-295), createdAt: isoOffset(-300) },
    ],
    photos: [],
  },
  {
    id: 'rental-14',
    carId: 'car-12',
    renterName: 'Bogdan',
    renterSurname: 'Constantin',
    renterCnp: '2900101140014',
    startDate: dateOffset(-20),
    endDate: dateOffset(-15),
    advancePayment: 320,
    status: 'completed',
    notes: 'Bancheta spate patata.',
    kmStart: 157200,
    kmEnd: 157850,
    createdAt: isoOffset(-20),
    updatedAt: isoOffset(-15),
    segments: [
      { id: 'seg-16', rentalId: 'rental-14', pricePerUnit: 330, priceUnit: 'day', startDate: dateOffset(-20), endDate: dateOffset(-15), createdAt: isoOffset(-20) },
    ],
    photos: [],
  },
  {
    id: 'rental-15',
    carId: 'car-12',
    renterName: 'Simona',
    renterSurname: 'Barbu',
    renterCnp: '1900101150015',
    startDate: dateOffset(-10),
    endDate: dateOffset(-8),
    advancePayment: 0,
    status: 'cancelled',
    notes: 'Rezervare anulata.',
    createdAt: isoOffset(-12),
    updatedAt: isoOffset(-11),
    segments: [
      { id: 'seg-17', rentalId: 'rental-15', pricePerUnit: 265, priceUnit: 'day', startDate: dateOffset(-10), endDate: dateOffset(-8), createdAt: isoOffset(-12) },
    ],
    photos: [],
  },
  {
    id: 'rental-16',
    carId: 'car-13',
    renterName: 'Florin',
    renterSurname: 'Enache',
    renterCnp: '2900101160016',
    startDate: dateOffset(-80),
    endDate: dateOffset(-60),
    advancePayment: 780,
    status: 'completed',
    notes: 'Stop dreapta crapat usor.',
    kmStart: 90000,
    kmEnd: 92800,
    createdAt: isoOffset(-80),
    updatedAt: isoOffset(-60),
    segments: [
      { id: 'seg-18', rentalId: 'rental-16', pricePerUnit: 950, priceUnit: 'week', startDate: dateOffset(-80), endDate: dateOffset(-60), createdAt: isoOffset(-80) },
    ],
    photos: [],
  },
  {
    id: 'rental-17',
    carId: 'car-8',
    renterName: 'Mihaela',
    renterSurname: 'Barbu',
    renterCnp: '1900101170017',
    startDate: dateOffset(-560),
    endDate: dateOffset(-554),
    advancePayment: 300,
    status: 'completed',
    notes: 'Capota matuita.',
    kmStart: 120500,
    kmEnd: 121200,
    createdAt: isoOffset(-560),
    updatedAt: isoOffset(-554),
    segments: [
      { id: 'seg-19', rentalId: 'rental-17', pricePerUnit: 140, priceUnit: 'day', startDate: dateOffset(-560), endDate: dateOffset(-554), createdAt: isoOffset(-560) },
    ],
    photos: [],
  },
  {
    id: 'rental-18',
    carId: 'car-11',
    renterName: 'Corina',
    renterSurname: 'Enescu',
    renterCnp: '2900101180018',
    startDate: dateOffset(-800),
    endDate: dateOffset(-794),
    advancePayment: 350,
    status: 'completed',
    notes: 'Bate pe spate la denivelari.',
    kmStart: 122500,
    kmEnd: 123700,
    createdAt: isoOffset(-800),
    updatedAt: isoOffset(-794),
    segments: [
      { id: 'seg-20', rentalId: 'rental-18', pricePerUnit: 200, priceUnit: 'day', startDate: dateOffset(-800), endDate: dateOffset(-794), createdAt: isoOffset(-800) },
    ],
    photos: [],
  },
  {
    id: 'rental-19',
    carId: 'car-2',
    renterName: 'Robert',
    renterSurname: 'Manea',
    renterCnp: '1900101190019',
    startDate: dateOffset(-380),
    endDate: dateOffset(-360),
    advancePayment: 450,
    status: 'completed',
    notes: 'Se aude ceva pe roata fata.',
    kmStart: 79500,
    kmEnd: 81800,
    createdAt: isoOffset(-380),
    updatedAt: isoOffset(-360),
    segments: [
      { id: 'seg-21', rentalId: 'rental-19', pricePerUnit: 550, priceUnit: 'week', startDate: dateOffset(-380), endDate: dateOffset(-360), createdAt: isoOffset(-380) },
    ],
    photos: [],
  },
  {
    id: 'rental-20',
    carId: 'car-8',
    renterName: 'Daniela',
    renterSurname: 'Costea',
    renterCnp: '2900101200020',
    startDate: dateOffset(-450),
    endDate: dateOffset(-435),
    advancePayment: 380,
    status: 'completed',
    notes: 'Portbagaj se inchide greu.',
    kmStart: 122000,
    kmEnd: 124100,
    createdAt: isoOffset(-450),
    updatedAt: isoOffset(-435),
    segments: [
      { id: 'seg-22', rentalId: 'rental-20', pricePerUnit: 900, priceUnit: 'week', startDate: dateOffset(-450), endDate: dateOffset(-435), createdAt: isoOffset(-450) },
    ],
    photos: [],
  },
  {
    id: 'rental-21',
    carId: 'car-11',
    renterName: 'Stefan',
    renterSurname: 'Voicu',
    renterCnp: '1900101210021',
    startDate: dateOffset(-220),
    endDate: dateOffset(-200),
    advancePayment: 1600,
    status: 'completed',
    notes: 'Jante dreapta zgariate.',
    kmStart: 133000,
    kmEnd: 136200,
    createdAt: isoOffset(-220),
    updatedAt: isoOffset(-200),
    segments: [
      { id: 'seg-23', rentalId: 'rental-21', pricePerUnit: 2800, priceUnit: 'week', startDate: dateOffset(-220), endDate: dateOffset(-200), createdAt: isoOffset(-220) },
    ],
    photos: [],
  },
  {
    id: 'rental-22',
    carId: 'car-3',
    renterName: 'Iulia',
    renterSurname: 'Croitoru',
    renterCnp: '2900101220022',
    startDate: dateOffset(-140),
    endDate: dateOffset(-125),
    advancePayment: 500,
    status: 'completed',
    notes: 'Senzor parcare spate intermitent.',
    kmStart: 161500,
    kmEnd: 163200,
    createdAt: isoOffset(-140),
    updatedAt: isoOffset(-125),
    segments: [
      { id: 'seg-24', rentalId: 'rental-22', pricePerUnit: 240, priceUnit: 'day', startDate: dateOffset(-140), endDate: dateOffset(-125), createdAt: isoOffset(-140) },
    ],
    photos: [],
  },
  {
    id: 'rental-23',
    carId: 'car-1',
    renterName: 'Bianca',
    renterSurname: 'Radulescu',
    renterCnp: '1900101230023',
    startDate: dateOffset(-110),
    endDate: dateOffset(-91),
    advancePayment: 550,
    status: 'completed',
    notes: 'Bara spate atinsa.',
    kmStart: 128500,
    kmEnd: 131500,
    createdAt: isoOffset(-110),
    updatedAt: isoOffset(-91),
    segments: [
      { id: 'seg-25', rentalId: 'rental-23', pricePerUnit: 165, priceUnit: 'day', startDate: dateOffset(-110), endDate: dateOffset(-91), createdAt: isoOffset(-110) },
    ],
    photos: [],
  },
  {
    id: 'rental-24',
    carId: 'car-6',
    renterName: 'Tudor',
    renterSurname: 'Serban',
    renterCnp: '2900101240024',
    startDate: dateOffset(-90),
    endDate: dateOffset(-69),
    advancePayment: 700,
    status: 'completed',
    notes: 'Stergatoare slabe.',
    kmStart: 85200,
    kmEnd: 86600,
    createdAt: isoOffset(-90),
    updatedAt: isoOffset(-69),
    segments: [
      { id: 'seg-26', rentalId: 'rental-24', pricePerUnit: 195, priceUnit: 'day', startDate: dateOffset(-90), endDate: dateOffset(-69), createdAt: isoOffset(-90) },
    ],
    photos: [],
  },
  {
    id: 'rental-25',
    carId: 'car-10',
    renterName: 'Alina',
    renterSurname: 'Popa',
    renterCnp: '1900101250025',
    startDate: dateOffset(-100),
    endDate: dateOffset(-83),
    advancePayment: 500,
    status: 'completed',
    notes: 'Frane vibreaza usor.',
    kmStart: 114000,
    kmEnd: 115700,
    createdAt: isoOffset(-100),
    updatedAt: isoOffset(-83),
    segments: [
      { id: 'seg-27', rentalId: 'rental-25', pricePerUnit: 175, priceUnit: 'day', startDate: dateOffset(-100), endDate: dateOffset(-83), createdAt: isoOffset(-100) },
    ],
    photos: [],
  },
  {
    id: 'rental-26',
    carId: 'car-13',
    renterName: 'Marius',
    renterSurname: 'Filip',
    renterCnp: '2900101260026',
    startDate: dateOffset(-45),
    endDate: dateOffset(-30),
    advancePayment: 400,
    status: 'completed',
    notes: 'Ambreiaj tine sus.',
    kmStart: 92500,
    kmEnd: 94200,
    createdAt: isoOffset(-45),
    updatedAt: isoOffset(-30),
    segments: [
      { id: 'seg-28', rentalId: 'rental-26', pricePerUnit: 180, priceUnit: 'day', startDate: dateOffset(-45), endDate: dateOffset(-30), createdAt: isoOffset(-45) },
    ],
    photos: [],
  },
  {
    id: 'rental-27',
    carId: 'car-9',
    renterName: 'Oana',
    renterSurname: 'Balan',
    renterCnp: '1900101270027',
    startDate: dateOffset(-50),
    endDate: dateOffset(-37),
    advancePayment: 350,
    status: 'completed',
    notes: 'Usa sofer zgariata.',
    kmStart: 67800,
    kmEnd: 68700,
    createdAt: isoOffset(-50),
    updatedAt: isoOffset(-37),
    segments: [
      { id: 'seg-29', rentalId: 'rental-27', pricePerUnit: 165, priceUnit: 'day', startDate: dateOffset(-50), endDate: dateOffset(-37), createdAt: isoOffset(-50) },
    ],
    photos: [],
  },
]

export const demoMaintenance: Maintenance[] = [
  {
    id: 'mnt-1',
    carId: 'car-3',
    type: 'repair',
    description: 'Inlocuire distributie completa (kit + pompa apa si intinzator)',
    cost: 1700,
    datePerformed: dateOffset(-2),
    serviceEndDate: dateOffset(3),
    blocksAvailability: true,
    kmAtService: 166500,
    notes: 'Kit distributie Contitech - 820 lei\nPompa apa Hepu - 260 lei\nCurea accesorii - 120 lei\nAntigel - 100 lei\nManopera - 400 lei',
    createdAt: isoOffset(-2),
    documents: [],
  },
  {
    id: 'mnt-2',
    carId: 'car-8',
    type: 'repair',
    description: 'Inlocuire ambreiaj si volanta bimasa',
    cost: 2200,
    datePerformed: dateOffset(-1),
    serviceEndDate: dateOffset(2),
    blocksAvailability: true,
    kmAtService: 131800,
    notes: 'Kit ambreiaj Sachs - 1500 lei\nUlei cutie - 150 lei\nManopera - 550 lei',
    createdAt: isoOffset(-1),
    documents: [],
  },
  {
    id: 'mnt-3',
    carId: 'car-10',
    type: 'repair',
    description: 'Diagnoza completa si inlocuire baterie',
    cost: 1000,
    datePerformed: dateOffset(0),
    serviceEndDate: dateOffset(5),
    blocksAvailability: true,
    kmAtService: 115900,
    notes: 'Diagnoza - 100 lei\nTest baterie - 50 lei\nBaterie Rombat - 500 lei\nManopera - 350 lei',
    createdAt: nowIso,
    documents: [],
  },
  {
    id: 'mnt-4',
    carId: 'car-1',
    type: 'other',
    description: 'Detailing interior si exterior complet',
    cost: 350,
    datePerformed: dateOffset(-280),
    serviceEndDate: dateOffset(-279),
    blocksAvailability: false,
    kmAtService: 126000,
    notes: 'Curatat interior - 200 lei\nSpalat tapiterie - 100 lei\nPolish faruri - 50 lei',
    createdAt: isoOffset(-280),
    documents: [],
  },
  {
    id: 'mnt-5',
    carId: 'car-2',
    type: 'repair',
    description: 'Revizie ulei si filtre',
    cost: 850,
    datePerformed: dateOffset(-300),
    serviceEndDate: dateOffset(-299),
    blocksAvailability: false,
    kmAtService: 79000,
    notes: 'Ulei Motul 5W30 5L - 280 lei\nFiltru ulei Mann - 40 lei\nFiltru aer Mahle - 70 lei\nFiltru habitaclu carbon - 120 lei\nFiltru combustibil Mann - 140 lei\nManopera - 200 lei',
    createdAt: isoOffset(-300),
    documents: [],
  },
  {
    id: 'mnt-6',
    carId: 'car-4',
    type: 'investment',
    description: 'Anvelope noi (set 4, vara)',
    cost: 1500,
    datePerformed: dateOffset(-50),
    serviceEndDate: dateOffset(-49),
    blocksAvailability: false,
    kmAtService: 121000,
    notes: 'Anvelope Goodyear EfficientGrip DOT 2025 - 1220 lei\nMontaj si echilibrat - 200 lei\nValve - 40 lei\nManopera - 40 lei',
    createdAt: isoOffset(-50),
    documents: [],
  },
  {
    id: 'mnt-7',
    carId: 'car-5',
    type: 'repair',
    description: 'Inlocuire baterie auto',
    cost: 650,
    datePerformed: dateOffset(-40),
    serviceEndDate: dateOffset(-39),
    blocksAvailability: false,
    kmAtService: 95500,
    notes: 'Test baterie - 50 lei\nBaterie Rombat - 500 lei\nManopera - 100 lei',
    createdAt: isoOffset(-40),
    documents: [],
  },
  {
    id: 'mnt-8',
    carId: 'car-6',
    type: 'investment',
    description: 'Reparatie suspensie fata (brate si tampoane)',
    cost: 1600,
    datePerformed: dateOffset(-195),
    serviceEndDate: dateOffset(-193),
    blocksAvailability: false,
    kmAtService: 84400,
    notes: 'Brat inferior stanga - 450 lei\nBrat inferior dreapta - 450 lei\nBielete antiruliu - 180 lei\nBucse bara stabilizatoare - 160 lei\nGeometrie - 180 lei\nManopera - 180 lei',
    createdAt: isoOffset(-195),
    documents: [],
  },
  {
    id: 'mnt-9',
    carId: 'car-7',
    type: 'other',
    description: 'Tinichigerie si vopsitorie bara fata',
    cost: 800,
    datePerformed: dateOffset(-70),
    serviceEndDate: dateOffset(-68),
    blocksAvailability: false,
    kmAtService: 58000,
    notes: 'Vopsit bara fata - 420 lei\nMateriale vopsitorie - 160 lei\nDemontat/montat bara - 120 lei\nManopera - 100 lei',
    createdAt: isoOffset(-70),
    documents: [],
  },
  {
    id: 'mnt-10',
    carId: 'car-9',
    type: 'repair',
    description: 'Placute si discuri frana fata/spate',
    cost: 950,
    datePerformed: dateOffset(-35),
    serviceEndDate: dateOffset(-34),
    blocksAvailability: false,
    kmAtService: 66500,
    notes: 'Placute fata ATE - 220 lei\nDiscuri fata ATE - 520 lei\nSenzor uzura - 40 lei\nManopera - 170 lei',
    createdAt: isoOffset(-35),
    documents: [],
  },
  {
    id: 'mnt-11',
    carId: 'car-11',
    type: 'investment',
    description: 'Schimb ulei cutie automata si filtru',
    cost: 2100,
    datePerformed: dateOffset(-660),
    serviceEndDate: dateOffset(-659),
    blocksAvailability: false,
    kmAtService: 131500,
    notes: 'Ulei cutie automata Ravenol - 850 lei\nFiltru cutie - 320 lei\nGarnitura baie - 180 lei\nCuratare baie ulei - 150 lei\nManopera - 600 lei',
    createdAt: isoOffset(-660),
    documents: [],
  },
  {
    id: 'mnt-12',
    carId: 'car-12',
    type: 'repair',
    description: 'Curatare sistem DPF si verificare supapa EGR',
    cost: 1900,
    datePerformed: dateOffset(-290),
    serviceEndDate: dateOffset(-288),
    blocksAvailability: false,
    kmAtService: 156700,
    notes: 'Diagnoza - 100 lei\nCuratare EGR - 350 lei\nCuratare DPF - 700 lei\nSolutie curatare admisie - 150 lei\nManopera - 600 lei',
    createdAt: isoOffset(-290),
    documents: [],
  },
  {
    id: 'mnt-13',
    carId: 'car-13',
    type: 'repair',
    description: 'Revizie ulei si filtre',
    cost: 650,
    datePerformed: dateOffset(-55),
    serviceEndDate: dateOffset(-54),
    blocksAvailability: false,
    kmAtService: 93000,
    notes: 'Ulei Motul 5W30 4L - 220 lei\nFiltru ulei Bosch - 35 lei\nFiltru aer Bosch - 55 lei\nFiltru habitaclu - 90 lei\nManopera - 250 lei',
    createdAt: isoOffset(-55),
    documents: [],
  },
  {
    id: 'mnt-14',
    carId: 'car-8',
    type: 'investment',
    description: 'Anvelope noi (set 4)',
    cost: 1600,
    datePerformed: dateOffset(-552),
    serviceEndDate: dateOffset(-551),
    blocksAvailability: false,
    kmAtService: 121000,
    notes: 'Anvelope Michelin Primacy DOT 2025 - 1300 lei\nMontaj si echilibrat - 200 lei\nValve - 40 lei\nManopera - 60 lei',
    createdAt: isoOffset(-552),
    documents: [],
  },
]

export const demoInvites: FleetAccess[] = [
  {
    id: 'acc-1',
    ownerId: 'demo-user',
    invitedEmail: 'coleg@mycars.ro',
    role: 'editor',
    createdAt: nowIso,
  },
]

// Notificarile nu se pastreaza static aici - data-service.ts (bootstrap) le
// regenereaza automat din demoDocuments (buildNotifications), pe baza datelor
// de expirare. Un array gol evita duplicarea intre notificari scrise manual
// si cele calculate automat pentru acelasi document.
export const demoNotifications: NotificationItem[] = []

export const demoFleetReports: FleetReportRecord[] = []
